barter/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('main.urls', namespace="main")),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^$',views.index, name='index'),
    url(r'^get_drugs/$', views.get_drugs, name='get_drugs'),
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^create_user/$', views.create_user, name='create_user'),
    url(r'^user_profile/$', views.user_profile, name='user_profile'),
    url(r'^results/(?P<item_id>[0-9]+)/$', views.results, name='results'),
    url(r'^view_item/(?P<item_id>[0-9]+)/$', views.view_item, name='view_item'),
    url(r'^confirm/(?P<notification_id>[0-9]+)/$', views.confirm, name='confirm'),
    url(r'^confirm_delete/(?P<notification_id>[0-9]+)/$', views.confirm_delete, name='confirm_delete'),
    url(r'^respond_to_notification/(?P<notification_id>[0-9]+)/$', views.respond_to_notification, name='respond_to_notification'),
    url(r'^view_other_profile/(?P<user_id>[0-9]+)/$', views.view_other_profile, name='view_other_profile'),
    url(r'^make_transaction/(?P<notification_id>[0-9]+)/$', views.make_transaction, name='make_transaction'),
    url(r'^new_item/$', views.new_item, name='new_item'),
    url(r'^edit_item/(?P<item_id>[0-9]+)/$', views.edit_item, name='edit_item'),

]

main/models.py
from __future__ import unicode_literals

from django.db import models
import re
from django.db import models
from django.core import validators
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import User, UserManager

class User(AbstractBaseUser, PermissionsMixin):

	class Meta:
		#app_label = 'accounts'
		db_table = "user"
		#ordering=["created"]

	username = models.CharField(_('username'), max_length=75, unique=True,
	help_text=_('Required. 30 characters or fewer. Letters, numbers and '
	'@/./+/-/_ characters'),
	validators=[
	validators.RegexValidator(re.compile('^[\w.@+-]+$'),
	_('Enter a valid username.'), 'invalid')
	])
	first_name = models.CharField(_('First Name'), max_length=254)
	last_name = models.CharField(_('short name'), max_length=30)
	email = models.EmailField(_('email address'), max_length=254, unique=True)
	is_staff = models.BooleanField(_('staff status'), default=False,
	help_text=_('Designates whether the user can log into this admin '
	'site.'))
	is_active = models.BooleanField(_('active'), default=True,
	help_text=_('Designates whether this user should be treated as '
	'active. Unselect this instead of deleting accounts.'))
	date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

	objects = UserManager()

	reputation = models.IntegerField(default = 0)

	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = ['email']

	profile_pic = models.ImageField(upload_to='profile_pics')


	def get_full_name(self):
		return self.full_name

	def get_short_name(self):
		return self.username

	def __unicode__(self):
		return self.username

class Category(models.Model):
    name = models.CharField(max_length = 400)
    description = models.TextField()
    users = models.ManyToManyField(User)

    class Meta:
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length = 400)
    description = models.TextField()
    owner = models.ForeignKey(User)
    category = models.ForeignKey(Category)
    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class Image(models.Model):
    img = models.ImageField(upload_to='item_images', blank=True, null=True)
    item = models.ForeignKey(Item, blank = True, null = True)

class Address(models.Model):
	user = models.OneToOneField(User)
	street = models.CharField(max_length = 100)
	city = models.CharField(max_length = 100)
	zip_code = models.CharField(max_length = 5)

class Notification(models.Model):
	to_user = models.ForeignKey(User, related_name = "to_user")
	from_user = models.ForeignKey(User, related_name = "from_user")
	to_user_item = models.ForeignKey(Item, related_name = "to_user_item")
	from_user_item = models.ForeignKey(Item)
	parent_notification = models.ForeignKey('self')

main/views.py
from django.shortcuts import render

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django import forms
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.template import RequestContext

from .models import User, Category, Image, Item, Notification
from .forms import UserProfileForm, CreateUserForm, AddressForm, ItemForm, EditItemForm
from random import shuffle

import json

# Create your views here.

def index(request):
    message = ''
    if 'message' in request.session:
        message = request.session["message"]

    items = []
    if not request.user.is_authenticated():
        all_items = list(Item.objects.all())
        shuffle(all_items)
        if len(all_items) > 10:
            items = all_items[0:10]
        else:
            items = all_items

    else:
        all_items = []
        user_interests = request.user.category_set.all()
        for interest in user_interests:
            all_items.extend(list(interest.item_set.all()))

        shuffle(all_items)
        if len(all_items) > 10:
            items = all_items[0:10]
        elif len(user_interests) == 0:
            all_items = Item.objects.all()
            shuffle(all_items)
            if len(all_items) > 10:
                items = all_items[0:10]
            else:
                items = all_items
        else:
            items = all_items


    if request.method == 'POST':
        data = request.POST.get('drugs')
        found_entries = Item.objects.get(name = data)
        if found_entries:
            item_id = found_entries.pk
            return HttpResponseRedirect(reverse("main:results", args = (item_id,)))
        else:
            request.session['search'] = data
            return HttpResponseRedirect(reverse("main:results"))

    return render(request, 'main/index.html', {'message':message, 'items':items})

def get_drugs(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        drugs = Item.objects.filter(name__icontains = q )[:20]
        data = []
        for drug in drugs:
            drug_json = {}
            drug_json['id'] = drug.pk
            drug_json['label'] = drug.name
            drug_json['value'] = drug.name
            data.append(drug_json)
    else:
        data = 'fail'

    mimetype = 'application/json'
    return JsonResponse(data, safe = False)



def results(request, item_id=0):
    if not item_id == 0
        found_item = get_object_or_404(Item, pk=item_id)
    else:
        search = request.session['search']
        items = Item.objects.get(name__icontains = search)
        shuffle(items)
        return render(request, 'main/results.html', {'items':items})

    items = []
    item_category = found_item.category
    if not request.user.is_authenticated():
        items_in_category = item_category.item_set.all()
        for item in items_in_category:
            items.append(item)
        shuffle(items)

    else:
        user_owns = request.user.category_set.all()
        users = item_category.users.all()
        extras = []
        for client in users:
            if client.pk == request.user.pk:
                continue
            client_wants = client.category_set.all()

            for possession in user_owns:
                for want in client_wants:
                    #If the client has what the user owns...
                    #Then add all of the items of that client under the category searched for
                    if want.pk == possession.pk:
                        client_has = client.item_set.all()
                        category_id = item_category.pk
                        for item in client_has:
                            if item.category.pk == category_id:
                                items.append(item)
                            else:
                                extras.append(item)
        shuffle(items)
        shuffle(extras)
        items.extend(extras)

    return render(request, 'main/results.html', {'items':items})

def view_item(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    logged_in = False
    error = ''
    images = item.image_set.all()
    interested_in = []
    other = []
    if request.user.is_authenticated():
        user_items = request.user.item_set.all()
        owner_interests = item.owner.category_set.all()
        for c_item in user_items:
            for interest in owner_interests:
                if c_item.category.pk == interest.pk:
                    interested_in.append(c_item)
                    break
            other.append(c_item)
        logged_in = True
    else:
        user_items = []


    if request.method == 'POST':
        if not request.POST.get("item"):
            error = "You did not select an item to trade for."
        else:
            notification = Notification()
            notification.from_user = request.user
            notification.to_user = item.owner
            notification.to_user_item = item
            notification.from_user_item = Item.objects.get(pk = request.POST.get("item"))
            notification.save()
            return HttpResponseRedirect(reverse('main:confirm', args=(notification.pk,))) #Go to the results page


    return render(request, 'main/view_item.html', {'item':item, 'images':images,'interested_in':interested_in, 'other':other, 'logged_in':logged_in,'error':error})

@login_required
def confirm(request, notification_id):
    notification = get_object_or_404(Notification, pk = notification_id)
    if request.method == 'POST':
        data = request.POST.get('confirm')
        if data == 'yes':
            return HttpResponseRedirect(reverse('main:index'))
        else:
            notification.delete()
            request.session['message'] = "You have cancelled your request of "+notification.to_user_item.name+" in exchange for "+notification.from_user_item.name
            return HttpResponseRedirect(reverse('main:index'))
    return render(request, 'main/confirm.html', {'notification':notification})

@login_required
def respond_to_notification(request, notification_id):
    notification = get_object_or_404(Notification, pk = notification_id)
    notification_history = []
    notification_history.append(notification)
    while not notification.parent_notification is None:
        notification = notification.parent_notification
        notification_history.append(notification)
    client_items = notification.to_user.item_set.all()
    if request.method == 'POST':
        if 'accept' in request.POST:
            return HttpResponseRedirect(reverse('main:make_transaction', args=(notification.pk,)))
        elif 'delete' in request.POST:
            return HttpResponseRedirect(reverse('main:confirm_delete', args=(notification.pk,)))

    return render(request, 'main/respond_to_notification.html', {'notifications':notification_history, 'client_items':client_items})

@login_required
def confirm_delete(request, notification_id):
    notification = get_object_or_404(Notification, pk = notification_id)
    if request.method == 'POST':
        data = request.POST.get('confirm')
        if data == 'yes':
            return HttpResponseRedirect(reverse('main:index'))
        else:
            notification.delete()
            request.session['message'] = "You have cancelled your request of "+notification.to_user_item.name+" in exchange for "+notification.from_user_item.name
            return HttpResponseRedirect(reverse('main:index'))
    return render(request, 'main/confirm_delete.html', {'notification':notification})


def create_user(request):
    if request.method == 'POST':
        user_form = CreateUserForm(request.POST)
        address_form = AddressForm(request.POST)
        if user_form.is_valid() and address_form.is_valid():
            return #create User
    else:
        user_form = CreateUserForm()
        address_form = AddressForm()

    return render(request, 'main/create_user.html', {'user_form':user_form,'address_form':address_form})


@login_required
def user_profile(request):
    user_notifications = request.user.notification_set.all()
    user = request.user
    address = user.address
    notifications = []
    profile_pic = user.profile_pic
    items = user.item_set.all()
    categories = user.category_set.all()

    for notification in user_notifications:
        notification_history = []
        notification_history.append(notification)
        while not notification.parent_notification is None:
            notification = notification.parent_notification
            notification_history.append(notification)
        notifications.append(notification_history)

    user_form = UserProfileForm(instance = user)
    address_form = AddressForm(instance = address)

    if request.method == 'POST':
        if 'category' in request.POST:
            submitted_category = request.POST['categories']
            category = Category.objects.get(name = submitted_category)
            if not category:
                message = 'Select a valid category'
            else:
                category.users.add(user)
        if 'delete_category' in request.POST:
            if not request.POST.get('category'):
                message = 'You did not select a category to delete'
            category = Category.objects.get(pk = request.POST.get('category'))
            category.delete()

        else:
            user_form = UserProfileForm(request.POST, instance = user)
            address_form = AddressForm(request.POST, instance = address)
            if user_form.is_valid() and address_form.is_valid():
                user_form.save()
                address_form.save()

main/templates/main/confirm.html
{% extends "main/base.html" %}
{% block title %}Confirm{%endblock%}
{% block content %}
You are requesting a trade between your {{notification.from_user_item.name}} and {{notification.to_user.username}}'s {{notification.to_user_item.name}}.
<br />
Are you sure that you wish to proceed?

<form action = "{%url 'main:confirm' notification.pk%}" method = "POST">
     {% csrf_token %}
    <input type = "radio" name = "confirm" value = "yes" checked="checked">Yes</br>
    <input type = "radio" name = "confirm" value = "no">No</br>
</form>

{%endblock%}

main/templates/main/confirm_delete.html
{% extends "main/base.html" %}
{% block title %}Confirm Deletion{%endblock%}
{% block content %}
You are deleting the exchange with the latest proposal of your {{notification.from_user_item.name}} for {{notification.to_user.username}}'s {{notification.to_user_item.name}} in its entirety.
<br />
Are you sure that you wish to proceed?

<form action = "{%url 'main:confirm_deletion' notification.pk%}" method = "POST">
     {% csrf_token %}
    <input type = "radio" name = "confirm" value = "yes" checked="checked">Yes</br>
    <input type = "radio" name = "confirm" value = "no">No</br>
</form>

{%endblock%}

main/templates/main/create_user.html
{% extends "main/base.html" %}
{% block title %}Home{%endblock%}
{% block content %}
<form action = "{%url 'main:create_user'%}" method = 'POST'>
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ address_form.as_p }}
  <input type = "submit" value = "Create User" />
</form>
{%endblock%}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block title %}Home{%endblock%}
{%block header%}
<!--Header section  -->
<div class="container" id="home">
  <div class="row text-center">
    <div class="col-md-12" >
      <h1 class="head-main">Trade On</h1>
      <br />
      <h2 class="head-sub-main">
        The Item Lives on in the Hands of your Community
      </h2>
      <!--<h3 class="head-last"> Lorem ipsum dolor sit ametLorem ipsum dolor sit amet</h3>-->
      <br />
      <br />
      <div class = "ui-widget" id="wrapper" >
        <form action = "{%url 'main:index' %}" method = "POST" >
          {% csrf_token %}
          <input type="text" id="drugs" name="drugs"/>
          <input type="submit" value="Search"/>
        </form>
      </div><!-- #wrapper -->
      <br />
      <br />

    </div>
  </div>
</div>
<!--End Header section  -->
<br />
<br />
<br />
{%endblock%}

{%block content%}
<br />
<br />
{{message}}
<br />
<br />
<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden; visibility: hidden;">
  <!-- Loading Screen -->
  <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
    <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
    <div style="position:absolute;display:block;background:url('/static/img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
  </div>
  <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden;">
    {%for item in items%}
    <div data-p="112.50" style="display: none;">
      <a href="{%url 'main:view_item' item.pk %}"><img data-u="image" src="{{item.image_set.first().img.url}}" /></a>
      <div data-u="caption" data-t="0" style="position: absolute; top: 320px; left: 30px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">{{item.name}}</div>
    </div>
    {%endfor%}
  </div>
  <!-- Bullet Navigator -->
  <div data-u="navigator" class="jssorb01" style="bottom:16px;right:16px;">
    <div data-u="prototype" style="width:12px;height:12px;"></div>
  </div>
  <!-- Arrow Navigator -->
  <span data-u="arrowleft" class="jssora02l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
  <span data-u="arrowright" class="jssora02r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
  <a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
</div>

<!-- #endregion Jssor Slider End -->
{%endblock%}

main/templates/main/new_item.html
{% extends "main/base.html" %}
{% block title %}New Item{%endblock%}
{% block content %}
{{error}}
<div class = "ui-widget" >
<form action = "{%url 'main:new_item'%}" method = "POST">
     {% csrf_token %}
     {{item_form.as_p}}
     <input type="text" id="categories" name="categories"/>
     <input type="submit" value="Create Item"/>

</form>

</div><!-- #wrapper -->

Category not listed?  Request to create a new one: <a href = "#">Request New Category</a>
{%endblock%}

main/templates/main/respond_to_notification.html
{% extends "main/base.html" %}
{% block title %}Home{%endblock%}
{% block content %}

Latest Request:
Your {{notifications[0].from_user_item.name}} for {{notifications[0].to_user.username}}'s  {{notifications[0].to_user_item.name}}

History:
<ul>
{%for i in range(1, len(notifications))%}
<li>Your {{notifications[i].from_user_item.name}} for {{notifications[i].to_user.username}}'s  {{notifications[i].to_user_item.name}}</li>
{%endfor%}
</ul>

<br />
<br />
If this is an acceptable trade, click below to proceed to the step of exchanging information.

<form action = "{%url 'main:respond_to_notification' notication.pk %}" method = 'POST'>
  {% csrf_token %}
  <input type = "submit" value = "Accept Latest Exchange" name = 'accept' />
</form>

<br />

Otherwise, have a look at the other items that your trade associate owns.  If none of them appeal to you, simply delete the exchange thread.
<br />
<ul>
{%for item in items%}
<li><a href = "{%url 'main:view_item' item.pk %}">{{item.name}}</a></li>
{%endfor%}
</ul>
<br />

<form action = "{%url 'main:respond_to_notification' notication.pk %}" method = 'POST'>
  {% csrf_token %}
  <input type = "submit" value = "Accept Latest Exchange" name = 'accept' />
</form>


{%endblock%}

main/templates/main/results.html
{% extends "main/base.html" %}
{% block title %}Results{%endblock%}
{%block searchbar%}

<div class = "ui-widget" id="wrapper" >
      <form action = "{%url 'main:index' %}" method = "POST" >
         {% csrf_token %}
        <input type="text" id="drugs" name="drugs"/>
        <input type="submit" value="Search"/>
      </form>
  </div><!-- #wrapper -->

{%endblock%}

{% block content %}
<br />
<br />
<br />

<!--Effect: Left to Right -->
{%for item in items%}
<div class="pic">
  <a href = "{%url 'main:view_item' item.pk %}">
    <img src="{{item.image_set.first().img.url}}" class="pic-image" alt="{{item.name}}"/>
    <span class="pic-caption left-to-right">
        <!--<h1 class="pic-title">Left to Right</h1>-->
        <p>{{item.name}}</p>
    </span>
</div>
</a>
{%endfor%}

<script>
  document.addEventListener("touchstart", function(){}, true);
</script>
{%endblock%}

main/templates/main/user_profile.html
{% extends "main/base.html" %}
{% block title %}User Profile{%endblock%}
{% block content %}
<p><img src ="{{profile_pic.url}}"></p>

<div id = "transparentInput">
<form action = "{%url 'main:user_profile'%}" method = 'POST'>
  {% csrf_token %}
  {{ user_form.as_p }}
</form>
<br />
<form action = "{%url 'main:user_profile'%}" method = 'POST'>
  {% csrf_token %}
  {{ address_form.as_p }}
  <input type = "submit" value = "Update Address">
</form>
</div>

<br />
Reputation: {{reputation}}

<br />
Exchange Notifications:


{%for notification_list in notifications%}
<p>Your {{notification_list[0].from_user_item.name}} for {{notification_list[0].to_user.username}}'s  {{notification_list[0].to_user_item.name}}
<ul>
  <li>History:</li>
  {%for i in range(1, len(notification_list))%}
  <li>Your {{notification_list[i].from_user_item.name}} for {{notification_list[i].to_user.username}}'s  {{notification_list[i].to_user_item.name}}</li>
  {%endfor%}
</ul>
</p>
{%endfor%}

<br />
Your Interests:

<form action = "{%url 'main:user_profile'%}" method = 'POST'>
  {% csrf_token %}
  {%for category in categories%}
  <li><input type = "radio" name = "item" value = "{{category.pk}}">{{category.name}}</input></li>
  {%endfor%}
  <input type="text" id="categories" name="categories"/>
  <input type = "submit" value = "Add Interest" name = "category">
  <input type = "submit" value = "Delete Interest" name = "delete_category">
</form>


<br />
Your Items:

<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden; visibility: hidden;">
  <!-- Loading Screen -->
  <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
    <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
    <div style="position:absolute;display:block;background:url('/static/img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
  </div>
  <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden;">
    {%for item in items%}
    <div data-p="112.50" style="display: none;">
      <a href="{%url 'main:view_item' item.pk %}"><img data-u="image" src="{{item.image_set.first().img.url}}" /></a>
      <div data-u="caption" data-t="0" style="position: absolute; top: 320px; left: 30px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">{{item.name}}</div>
    </div>
    {%endfor%}
  </div>
  <!-- Bullet Navigator -->
  <div data-u="navigator" class="jssorb01" style="bottom:16px;right:16px;">
    <div data-u="prototype" style="width:12px;height:12px;"></div>
  </div>
  <!-- Arrow Navigator -->
  <span data-u="arrowleft" class="jssora02l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
  <span data-u="arrowright" class="jssora02r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
  <a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
</div>


</ul>


{%endblock%}

main/templates/main/view_item.html
{% extends "main/base.html" %}
{% block title %}View Item{%endblock%}
{%block specific%}

<style type="text/css">
#list_container {
  width:75%;
  background:#FFFFCC;
}
.items_list {
  float:left;
  width:49.9%;
}
.items_list div {border:1px solid #000}
</style>

{%endblock%}
{%block searchbar%}

<div class = "ui-widget" id="wrapper" >
      <form action = "{%url 'main:index' %}" method = "POST" >
         {% csrf_token %}
        <input type="text" id="drugs" name="drugs"/>
        <input type="submit" value="Search"/>
      </form>
  </div><!-- #wrapper -->

{%endblock%}
{% block content %}
<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden; visibility: hidden;">
  <!-- Loading Screen -->
  <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
    <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
    <div style="position:absolute;display:block;background:url('/static/img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
  </div>
  <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden;">
    {%for image in images%}
    <div data-p="112.50" style="display: none;">
      <a href="{%url 'main:view_item' item.pk %}"><img data-u="image" src="{{image.img.url}}" /></a>
    </div>
    {%endfor%}
  </div>
  <!-- Bullet Navigator -->
  <div data-u="navigator" class="jssorb01" style="bottom:16px;right:16px;">
    <div data-u="prototype" style="width:12px;height:12px;"></div>
  </div>
  <!-- Arrow Navigator -->
  <span data-u="arrowleft" class="jssora02l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
  <span data-u="arrowright" class="jssora02r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
  <a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
</div>


<h3>{{item.name}}</h3>
<p>{{item.owner}}</p>
<br />
<p>{{item.description}}</p>

<br />
<br />
{%if logged_in%}
{%if error%}{{error}}{%endif%}

  On the left are items that you own that this item's owner may be interested in,
  and on the right are other items that you own that this item's owner has not indicated
  an interest in.

<form action = "{%url 'main:view_item' item.pk%}" method="POST">
  {% csrf_token %}
  <div id="list_container">
    <div class="items_list">
      <div>
        <ul>
          {%for item in interested_in%}
          <li><input type = "radio" name = "item" value = "{{item.pk}}">{{item.name}}</input></li>
          {%endfor%}
        </ul>
      </div>
    </div>

    <div class="items_list">
      <div>
        <ul>
          {%for item in other%}
          <li><input type = "radio" name = "item" value = "{{item.pk}}">{{item.name}}</input></li>
          {%endfor%}
        </ul>
      </div>
    </div>
  </div>

  <input type = "submit" value = "Request a Trade">
</form>
{%endif%}

{%endblock%}

main/templates/main/view_other_profile.html
{% extends "main/base.html" %}
{% block title %}Home{%endblock%}
{% block content %}

<ul>
  <li>Username: {{username}}</li>
  <li>{{first_name}} {{last_name}}</li>
</ul>
<br />
{%if error%}{{error}}{%endif%}
<br />
User possessions:
<br />

<!--Effect: Left to Right -->
<div class="pic">
    <img src="/static/img/003.jpg" class="pic-image" alt="Pic"/>
    <span class="pic-caption left-to-right">
        <h1 class="pic-title">Left to Right</h1>
        <p>Hi, this is a simple example =D</p>
    </span>
</div>

<ul>
  {%for item in items%}
    <li><a href = "{%url 'main:view_item' item.pk}%}"></li>
  {%endfor%}
</ul>


{%endblock%}